name: Build
on:
  workflow_run:
    workflows: ["Dependabot auto-merge"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: andrewmhub/insurgency-sandstorm:latest