name: Docker Image CI
description: build insurgency-sandstorm
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 23 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check new version
        id: status
        run: |
          #!/bin/bash
          LOCALAPPVER=$(cat sandstorm.version)
          REMOTEAPPVER=$(curl -s -X GET 'https://api.steamcmd.net/v1/info/581330' | jq -r -e '.data."581330".depots."581333".manifests.public')
          if [[ "$LOCALAPPVER" != "$REMOTEAPPVER" ]]; then
          echo "$REMOTEAPPVER" > sandstorm.version
          exit 0
          else
          exit 1
          fi
        shell: bash
      -
        name: Login to DockerHub
        if: steps.status.outcome == 'success'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        if: steps.status.outcome == 'success'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: andrewmhub/insurgency-sandstorm:latest